import { Injectable } from '@angular/core';
import { faCalendar, faChevronDown, faChevronRight, faCircle, faCloudDownloadAlt, faCoins,
  faDotCircle, faMars, faStar, faSyncAlt, faVenus, faColumns, faStream, faChevronLeft, faLayerGroup,
  faDownload, faPaperclip, faCheck, faChevronUp, faEllipsisV, faBuilding, faStoreAlt, faCity,
  faBoxOpen, faBoxes, faCogs, faShield, faPercent, faWarehouse, faClipboardList, faFileImport,
  faFileExport, faCashRegister, faUniversity, faBriefcase, faUsers, faShoppingCart, faCog,
  faFilter, faCheckSquare, faSpinner, faFile, faUser } from '@fortawesome/pro-regular-svg-icons';
import { faCopy, faEye, faEyeSlash, faPencil, faPlus, faSearch, faSearchMinus, faSearchPlus,
  faTag, faTimes, faTrashAlt, faMinus, faFolderOpen, faBarcodeRead, faExclamationTriangle,
  faInfoCircle, faStar as fasStar, faFilePlus, faMinusCircle } from '@fortawesome/pro-solid-svg-icons';

@Injectable({
  providedIn: 'root'
})
export class Global {
  icon = {
    alert: faExclamationTriangle,
    arrowDown: faChevronDown,
    arrowLeft: faChevronLeft,
    arrowRight: faChevronRight,
    arrowUp: faChevronUp,
    attach: faPaperclip,
    bank_register: faUniversity,
    barcode: faBarcodeRead,
    basket: faShoppingCart,
    brand: faShield,
    business_casefile: faBriefcase,
    crm_casefile: faBriefcase,
    calendar: faCalendar,
    cash_register: faCashRegister,
    certificate_inventory_control: faClipboardList,
    check: faCheck,
    checkedCircle: faDotCircle,
    checkSquare: faCheckSquare,
    circle: faCircle,
    clipboard: faClipboardList,
    close: faTimes,
    cloud: faCloudDownloadAlt,
    cog: faCog,
    cogs: faCogs,
    coins: faCoins,
    company_group: faCity,
    company_shop: faStoreAlt,
    company: faBuilding,
    copy: faCopy,
    discount: faPercent,
    download: faDownload,
    employee: faUsers,
    eye_slash: faEyeSlash,
    eye: faEye,
    female: faVenus,
    file: faFile,
    filePlus: faFilePlus,
    filter: faFilter,
    folder: faFolderOpen,
    fullStar: fasStar,
    hide: faSearchMinus,
    incoming_certificate: faFileImport,
    info: faInfoCircle,
    kanban: faColumns,
    layers: faLayerGroup,
    male: faMars,
    menu: faEllipsisV,
    minus: faMinus,
    outgoing_certificate: faFileExport,
    pencil: faPencil,
    plus: faPlus,
    product_category: faBoxes,
    product: faBoxOpen,
    radioBlank: faCircle,
    radioSelected: faDotCircle,
    search: faSearch,
    separated_list: faStream,
    show: faSearchPlus,
    spinner: faSpinner,
    star: faStar,
    sync: faSyncAlt,
    tag: faTag,
    times: faTimes,
    trash: faTrashAlt,
    user: faUser,
    users: faUsers,
    warehouse: faWarehouse,
    warning: faExclamationTriangle,
    minus_circle: faMinusCircle,
  };
}
