import { Injectable } from '@angular/core';
import { faBarcode, faBoxes, faBoxOpen, faBriefcase, faBuilding, faCalendar, faCashRegister, faCheck,
  faCheckSquare, faChevronDown, faChevronLeft, faChevronRight, faChevronUp, faCircle, faCity,
  faClipboardList, faCloudDownloadAlt, faCog, faCogs, faCoins, faColumns, faCopy, faDotCircle,
  faDownload, faEllipsisV, faExclamationTriangle, faEye, faEyeSlash, faFile, faFileExport,
  faFileImport, faFileUpload, faFilter, faFolderOpen, faInfoCircle, faLayerGroup, faMars, faMinus, faMinusCircle,
  faPaperclip, faPencilAlt, faPercent, faPlus, faSearch, faSearchMinus, faSearchPlus, faShieldAlt, faShoppingCart, faSpinner,
  faStar, faStoreAlt, faStream, faSyncAlt, faTag, faTimes, faTrashAlt, faUniversity, faUser, faUsers,
  faVenus, faWarehouse } from '@fortawesome/free-solid-svg-icons';

@Injectable({
  providedIn: 'root'
})
export class Global {
  icon = {
    alert: faExclamationTriangle,
    arrowDown: faChevronDown,
    arrowLeft: faChevronLeft,
    arrowRight: faChevronRight,
    arrowUp: faChevronUp,
    attach: faPaperclip,
    bank_register: faUniversity,
    barcode: faBarcode,
    basket: faShoppingCart,
    brand: faShieldAlt,
    business_casefile: faBriefcase,
    crm_casefile: faBriefcase,
    calendar: faCalendar,
    cash_register: faCashRegister,
    certificate_inventory_control: faClipboardList,
    check: faCheck,
    checkedCircle: faDotCircle,
    checkSquare: faCheckSquare,
    circle: faCircle,
    clipboard: faClipboardList,
    close: faTimes,
    cloud: faCloudDownloadAlt,
    cog: faCog,
    cogs: faCogs,
    coins: faCoins,
    company_group: faCity,
    company_shop: faStoreAlt,
    company: faBuilding,
    copy: faCopy,
    discount: faPercent,
    download: faDownload,
    employee: faUsers,
    eye_slash: faEyeSlash,
    eye: faEye,
    female: faVenus,
    file: faFile,
    filePlus: faFileUpload,
    filter: faFilter,
    folder: faFolderOpen,
    fullStar: faStar,
    hide: faSearchMinus,
    incoming_certificate: faFileImport,
    info: faInfoCircle,
    kanban: faColumns,
    layers: faLayerGroup,
    male: faMars,
    menu: faEllipsisV,
    minus: faMinus,
    outgoing_certificate: faFileExport,
    pencil: faPencilAlt,
    plus: faPlus,
    product_category: faBoxes,
    product: faBoxOpen,
    radioBlank: faCircle,
    radioSelected: faDotCircle,
    search: faSearch,
    separated_list: faStream,
    show: faSearchPlus,
    spinner: faSpinner,
    star: faStar,
    sync: faSyncAlt,
    tag: faTag,
    times: faTimes,
    trash: faTrashAlt,
    user: faUser,
    users: faUsers,
    warehouse: faWarehouse,
    warning: faExclamationTriangle,
    minus_circle: faMinusCircle,
  };
}
